# Configuration Spring Boot pour Docker
spring:
  application:
    name: equipements-service
  
  # Configuration base de données
  datasource:
    url: jdbc:mysql://mysql:3306/equipements_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${SPRING_DATASOURCE_USERNAME:equipuser}
    password: ${SPRING_DATASOURCE_PASSWORD:equippass}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  # Configuration JPA
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

# Configuration serveur
server:
  port: ${SERVER_PORT:8085}
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# Configuration JWT
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789}
  expiration: 86400000

# Configuration CORS
cors:
  allowed-origins: 
    - http://localhost:4200
    - http://localhost:80
    - http://frontend:80
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Configuration Actuator pour monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true

# Configuration logging
logging:
  level:
    tn.esprit.equip: INFO
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
